version: '3.8'

services:
  web:
    build:
      context: ./RollTheDice
      dockerfile: ../Dockerfile.prod
    command: gunicorn RollTheDice.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/RollTheDice/web/staticfiles
      - media_volume:/home/RollTheDice/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/RollTheDice/web/staticfiles
      - media_volume:/home/RollTheDice/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data:
  static_volume:
  media_volume: