version: '3.8'

services:
  web:
    build: ./RollTheDice
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./RollTheDice/:/usr/src/RollTheDice/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=RollTheDice
      - POSTGRES_PASSWORD=rollthedice
      - POSTGRES_DB=RollTheDice_dev

volumes:
  postgres_data: