# Generated by Django 4.2 on 2024-06-01 17:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Partidas', '0002_alter_jugador_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jugador',
            unique_together={('usuario', 'partida')},
        ),
    ]
