# Generated by Django 4.2 on 2024-06-02 14:54

from django.db import migrations
from django.contrib.auth import get_user_model

def crear_usuario_administrador(apps, schema_editor):
    MyUser = get_user_model()
    MyUser.objects.create_superuser(
        email='admin@admin.com',
        name='admin',
        password='admin'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_usuario_administrador),
    ]
