# Generated by Django 4.2 on 2024-04-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descripcion')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.myuser', verbose_name='Usuario_creador')),
            ],
        ),
    ]
